export const flowers = [
  {
    id: 'rose',
    name: 'Rose',
    meaning: 'Love & Romance',
    scent: 'Classic floral, sweet and slightly spicy',
    birthMonth: 'June',
    occasions: ['love', 'anniversary', 'birthday'],
    color: '#e84057',
    accent: '#ff8fa3',
    leafColor: '#4a7c59',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    meaning: 'Happiness & Loyalty',
    scent: 'Earthy, warm with nutty undertones',
    birthMonth: 'August',
    occasions: ['congratulations', 'justbecause', 'birthday'],
    color: '#ffd700',
    accent: '#ffeb3b',
    leafColor: '#558b2f',
  },
  {
    id: 'tulip',
    name: 'Tulip',
    meaning: 'Perfect Love & Grace',
    scent: 'Light, fresh and green',
    birthMonth: 'March',
    occasions: ['love', 'apology', 'mothersday'],
    color: '#ff6b6b',
    accent: '#ffa07a',
    leafColor: '#4caf50',
  },
  {
    id: 'daisy',
    name: 'Daisy',
    meaning: 'Innocence & Purity',
    scent: 'Mild, fresh and herbaceous',
    birthMonth: 'April',
    occasions: ['getwell', 'justbecause', 'birthday'],
    color: '#ffffff',
    accent: '#ffd700',
    leafColor: '#66bb6a',
  },
  {
    id: 'lily',
    name: 'Lily',
    meaning: 'Purity & Devotion',
    scent: 'Rich, sweet and intoxicating',
    birthMonth: 'May',
    occasions: ['anniversary', 'congratulations', 'mothersday'],
    color: '#fff5ee',
    accent: '#ffb6c1',
    leafColor: '#2e7d32',
  },
  {
    id: 'peony',
    name: 'Peony',
    meaning: 'Romance & Prosperity',
    scent: 'Rich, sweet and slightly citrusy',
    birthMonth: 'May',
    occasions: ['love', 'anniversary', 'mothersday'],
    color: '#f8bbd0',
    accent: '#f48fb1',
    leafColor: '#388e3c',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    meaning: 'Devotion & Serenity',
    scent: 'Calming, herbal and slightly sweet',
    birthMonth: 'July',
    occasions: ['getwell', 'thankyou', 'justbecause'],
    color: '#b39ddb',
    accent: '#9575cd',
    leafColor: '#7cb342',
  },
  {
    id: 'orchid',
    name: 'Orchid',
    meaning: 'Luxury & Elegance',
    scent: 'Delicate, exotic and slightly vanilla',
    birthMonth: 'November',
    occasions: ['congratulations', 'anniversary', 'love'],
    color: '#ce93d8',
    accent: '#ab47bc',
    leafColor: '#33691e',
  },
  {
    id: 'carnation',
    name: 'Carnation',
    meaning: 'Admiration & Gratitude',
    scent: 'Spicy-sweet, similar to clove',
    birthMonth: 'January',
    occasions: ['thankyou', 'mothersday', 'birthday'],
    color: '#ef5350',
    accent: '#e57373',
    leafColor: '#43a047',
  },
  {
    id: 'iris',
    name: 'Iris',
    meaning: 'Wisdom & Hope',
    scent: 'Powdery, sweet and slightly woody',
    birthMonth: 'February',
    occasions: ['graduation', 'getwell', 'congratulations'],
    color: '#5c6bc0',
    accent: '#7986cb',
    leafColor: '#558b2f',
  },
  {
    id: 'chrysanthemum',
    name: 'Chrysanthemum',
    meaning: 'Joy & Longevity',
    scent: 'Fresh, herbal and slightly camphor-like',
    birthMonth: 'November',
    occasions: ['birthday', 'congratulations', 'getwell'],
    color: '#ffc107',
    accent: '#ffca28',
    leafColor: '#689f38',
  },
  {
    id: 'anemone',
    name: 'Anemone',
    meaning: 'Anticipation & Protection',
    scent: 'Light, delicate, almost ethereal',
    birthMonth: 'September',
    occasions: ['justbecause', 'apology', 'love'],
    color: '#90caf9',
    accent: '#64b5f6',
    leafColor: '#2e7d32',
  },
];

export const occasions = [
  { id: 'birthday', label: 'Birthday', emoji: '🎂' },
  { id: 'thankyou', label: 'Thank You', emoji: '🙏' },
  { id: 'getwell', label: 'Get Well', emoji: '💝' },
  { id: 'justbecause', label: 'Just Because', emoji: '💐' },
  { id: 'congratulations', label: 'Congratulations', emoji: '🎉' },
  { id: 'apology', label: "I'm Sorry", emoji: '🕊️' },
  { id: 'love', label: 'Love', emoji: '❤️' },
  { id: 'anniversary', label: 'Anniversary', emoji: '💍' },
  { id: 'mothersday', label: "Mother's Day", emoji: '👩' },
  { id: 'graduation', label: 'Graduation', emoji: '🎓' },
];

export const themes = [
  { id: 'classic', name: 'Classic', bg: '#faf8f5', text: '#2d2a26', accent: '#e84057', cardBg: '#ffffff' },
  { id: 'romantic', name: 'Romantic', bg: '#fff0f5', text: '#4a2030', accent: '#ff69b4', cardBg: '#fff5f9' },
  { id: 'spring', name: 'Spring Garden', bg: '#f0fff4', text: '#1a3a2a', accent: '#48bb78', cardBg: '#f7fff9' },
  { id: 'sunset', name: 'Golden Sunset', bg: '#fff8f0', text: '#3d2a1a', accent: '#ff8c42', cardBg: '#fffaf5' },
  { id: 'midnight', name: 'Midnight', bg: '#1a1a2e', text: '#e8e8f0', accent: '#e2b0ff', cardBg: '#252540' },
  { id: 'ocean', name: 'Ocean Breeze', bg: '#e8f4f8', text: '#1a3040', accent: '#4a90d9', cardBg: '#f0f8ff' },
];

export const closings = [
  'Sincerely,',
  'With love,',
  'XOXO,',
  'Yours truly,',
  'Forever yours,',
  'Warmly,',
  'Cheers,',
  'With gratitude,',
  'Always,',
  'With all my heart,',
];

export function suggestFlowers(occasionId) {
  return flowers.filter(f => f.occasions.includes(occasionId));
}
